version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: habits-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - habits-network
    depends_on:
      - mysql
      - redis

  node:
    image: node:20-alpine
    container_name: habits-node
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - habits-network
    command: sh -c "npm install && npm run dev"
    ports:
      - "5173:5173"

  nginx:
    image: nginx:alpine
    container_name: habits-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - habits-network
    depends_on:
      - app

  mysql:
    image: mysql:8.0
    container_name: habits-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: habits
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: password
      MYSQL_USER: habits
      SERVICE_NAME: mysql
    volumes:
      - habits-mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - habits-network

  redis:
    image: redis:alpine
    container_name: habits-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - habits-network
    volumes:
      - habits-redis:/data

networks:
  habits-network:
    driver: bridge

volumes:
  habits-mysql:
    driver: local
  habits-redis:
    driver: local 